<section class="invoice"> 
        <div class="row">
          <div class="col-xs-12">
            <h2 class="page-header">
              <i class="fa fa-globe"></i> Ndrugs, Inc.
              <small class="pull-right">Date: <?php echo date("d/m/Y");?></small>
            </h2>
          </div><!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
          <div class="col-sm-4 invoice-col">
            From
            <address>
              <strong>Ndrugs, Inc.</strong><br>
              795 Folsom Ave, Suite 600<br>
              San Francisco, CA 94107<br>
              Phone: (804) 123-5432<br/>
              Email: hello@almasaeedstudio.com
            </address>
          </div><!-- /.col -->
          <div class="col-sm-4 invoice-col">
            To

            <address>
              <strong><?php echo ucwords($this->Order->shipping_address->name); ?></strong><br>
              <?php echo ucwords($this->Order->shipping_address->street1); ?> , <?php echo ucwords($this->Order->shipping_address->street2); ?> <br>
              <?php echo ucwords($this->Order->shipping_address->city); ?> , <?php echo ucwords($this->Order->shipping_address->state); ?>  <?php echo ucwords($this->Order->shipping_address->pincode); ?> , ( <?php echo ucwords($this->Order->shipping_address->country); ?> ) <br>
              Phone: (555) 539-1037<br/>
              Email: <?php echo $this->Order->user->email; ?>
            </address>  
          </div><!-- /.col -->
          <div class="col-sm-4 invoice-col">
            <b>Invoice #<?php echo $this->Order->id; ?></b><br/>
            <br/>
            <b>Order ID:</b> <?php echo $this->Order->id; ?><br/>
            <b>Order Date:</b> <?php //echo $this->Order->created->format ("Y-m-d H:i:s"); ?><br/>
            <b>Account:</b> <?php echo $this->Order->user->id; ?>
          </div><!-- /.col -->
        </div><!-- /.row -->

        <!-- Table row -->
        <div class="row">
          <div class="col-xs-12 table-responsive">
            <table class="table table-hover">
                  <tbody>
                      <tr>
                      <th>ID</th>
                      <th>Product</th> 
                      <th>MRP</th>
                      <th>Sell Price</th>
                      <th>Qty</th>
                      <th>Subtotal</th>
                      <th>Item Status</th>
                    </tr>
                    <?php 
                    $GrandTotal = 0;
                    foreach ($this->Items as $key => $Item) { 
                          $GrandTotal = $GrandTotal + ( $Item->qty*$Item->price ); 
                           ?> 
                          <tr>
                            <td><?php echo $Item->id; ?></td>
                            <td><a href="catalog/product/view?id=?<?php echo $Item->product->id; ?>" >  <?php echo ucwords($Item->product->name); ?> </a> 
                            </td>
                            <td><?php echo "Rs. ".$Item->product->MRP; ?></td>
                            <td><?php echo "Rs. ".$Item->price; ?></td>
                            <td><?php echo $Item->qty; ?></td>
                            <td><?php echo ($Item->qty*$Item->price); ?></td>
                            <td>
                            <span class="label label-success"><?php echo ucwords($Item->status); ?></span></td>
                          </tr>   
                      <?php } ?> 
                      <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>Grand Total : </th>
                            <th<?php echo "Rs.".$GrandTotal."/-"; ?> </th>
                            <th></th>
                      </tr>  

                  </tbody>
                  </table> 
          </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="row">
          <!-- accepted payments column -->
          <div class="col-xs-6">
            <p class="lead">Payment Methods:</p>
            <img src="/img/credit/visa.png" alt="Visa"/>
            <img src="/img/credit/mastercard.png" alt="Mastercard"/>
            <img src="/img/credit/american-express.png" alt="American Express"/>
            <img src="/img/credit/paypal2.png" alt="Paypal"/>
            <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
              Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
            </p>
          </div><!-- /.col -->
          <div class="col-xs-6">
            <p class="lead">Amount Due <?php echo date("d/m/Y");?></p> 
          </div><!-- /.col -->
        </div><!-- /.row -->
      </section><!-- /.content -->