<section class="invoice"> 
        <div class="row">
          <div class="col-xs-12">
            <h2 class="page-header">
               <img src="/img/logo-blk.png">
              <small class="pull-right">Date: <?php echo date("d/m/Y");?>
              <img src="/barcode.png?q=<?php echo $this->orders->id; ?>-<?php echo $this->Items->id; ?>" />
              </small>
            </h2>            
          </div><!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
          <div class="col-sm-4 invoice-col">
            From : 
            <address>
              <?php echo $this->from; ?> 
            </address>
          </div><!-- /.col -->
          <div class="col-sm-4 invoice-col">
            To :
            <address>
              <strong><?php echo ucwords($this->orders->shipping_address->name); ?></strong><br>
              <?php echo ucwords($this->orders->shipping_address->street1); ?> , <?php echo ucwords($this->orders->shipping_address->street2); ?> <br>
              <?php echo ucwords($this->orders->shipping_address->city); ?> , <?php echo ucwords($this->orders->shipping_address->state); ?>  <?php echo ucwords($this->orders->shipping_address->pincode); ?> , ( <?php echo ucwords($this->orders->shipping_address->country); ?> ) <br>
              Phone: <?php echo $this->orders->shipping_address->contactno; ?><br/>
              Email: <?php echo $this->orders->user->email; ?>
            </address>  
          </div><!-- /.col -->
          <div class="col-sm-4 invoice-col">
            <b>Invoice #<?php echo $this->orders->id; ?></b><br/>
            <br/>
            <b>Order ID:</b> <?php echo $this->orders->id; ?><br/>
            <b>SubOrder ID:</b> <?php echo $this->orders->id; ?><?php echo $this->Items->id; ?><br/>
            <b>Order Date:</b> <?php echo $this->orders->created->format ("Y-m-d H:i:s"); ?><br/>
            <b>Account Paid:</b> <?php echo $this->paidTotal; ?></br>
            <b>Account Due:</b> <?php echo $this->unpaidTotal; ?>
            </div><!-- /.col -->
        </div><!-- /.row -->

        <!-- Table row -->
        <div class="row">
          <div class="col-xs-12 table-responsive">
            <table class="table">
                  <tbody>
                      <tr>
                      <th>ID</th>
                      <th>Product</th>  
                      <th>MRP</th>
                      <th>Sell Price</th>
                      <th>Qty</th>
                      <th>Subtotal</th>
                    </tr>
                    <tr>
                      <td><?php echo $this->Items->id; ?></td>
                      <td><?php echo ucwords($this->Items->product->name); ?></td> 
                      <td><?php echo "Rs. ".$this->Items->product->MRP; ?></td>
                      <td><?php echo "Rs. ".$this->Items->price; ?></td>
                      <td><?php echo $this->Items->qty; ?></td>
                      <td><?php echo ($this->Items->qty*$this->Items->price); ?></td>
                    </tr>   
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th> 
                        <th colspan = "4" > 
                              <table class="table">
                                    <tbody> 
                                    <tr >
                                      <td>Subtotal : </td> 
                                      <td class="tr_subtotal"><?php echo $this->Subtotal; ?></td>
                                    </tr>
                                    <tr>
                                      <td >Shiping Charge :</td> 
                                      <td  class="tr_shiping" ><?php echo $this->ShipingCharge; ?></td>
                                    </tr> 

                                    <tr>
                                      <td >Offer Price :</td> 
                                      <td class="tr_offer"><?php echo $this->OfferPrice; ?></td>
                                    </tr> 


                                    <tr  >
                                      <td>Grand Total :</td> 
                                      <td ><span class="badge bg-green tr_grand " ><?php echo $this->GrandTotal; ?></span></td>
                                    </tr>  
                                  </tbody>
                              </table>
                    </th>
                  </tr>   
                  </tbody>
                  </table> 
          </div><!-- /.col -->
        </div><!-- /.row -->

        <div class="row"> 
          <!-- accepted payments column -->
          <div class="col-xs-6">
            <p class="lead">Payment Methods:</p>
            <!-- <img src="/img/credit/visa.png" alt="Visa"/> -->
            <!-- <img src="/img/credit/mastercard.png" alt="Mastercard"/> -->
            <!-- <img src="/img/credit/american-express.png" alt="American Express"/> -->
            <!-- <img src="/img/credit/paypal2.png" alt="Paypal"/> -->
            <img src="/img/credit/cod.jpg" alt="COD" width="70px" /> 
             
           <!--  <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
              Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem plugg dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
            </p> -->
          </div><!-- /.col -->
          <div class="col-xs-6">
            <p class="lead"><b>Amount Due <?php echo $this->unpaidTotal; ?> on <?php echo date("d/m/Y");?></b></p> 
          </div><!-- /.col -->
        </div><!-- /.row -->
      </section><!-- /.content -->