  <div class="row">
    <div class="col-md-3"> 
        <div class="row">
          <div class="col-md-12">
            <a href="/ops/index/index" class=" btn btn-primary btn-block margin-bottom">Back to Order List</a>
          </div> 
        </div>  
    <div class="box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title">Order Information</h3>
      </div>
      <div class="box-body no-padding"> 
        <ul class="nav nav-pills nav-stacked">
          <li <?php if($this->info){ echo 'class="active"'; } ?>  ><a href="/ops/index/sub-order?type=info" ><i class="fa fa-flash"></i> Information </a></li>  
          <!-- <li <?php if($this->print){ echo 'class="active"'; } ?> ><a  href="/ops/index/sub-order?type=print"><i class="fa fa-print"></i> Print </a></li>  -->


        </ul>
      </div> 
    </div> 
  </div> 
  <div class="col-md-9">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Order Information</h3>

         <a href="/ops/index/print?order=<?php echo $this->Order->id; ?>" target="_blank" class="btn pull-right btn-primary"><i class="fa fa-print"></i> Print Order Details </a>

      </div> 
      <div class="box-body"> 
        <!--  end info  -->
        <?php    
           if($this->info){  
        ?> 
         <div class="row">
          <div class="col-md-6" > 
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Order # <?php echo $this->Order->id; ?></h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tbody><tr>
                     
                      <th>Order Date</th>
                      <th><?php echo $this->Order->created->format ("Y-m-d H:i:s"); ?></th> 
                    </tr>
                    <tr>
                      <td>Order Status</td> 
                      <td><span class="badge bg-red"><?php echo ucwords($this->Order->status); ?></span></td>
                    </tr>  

                    <tr>
                      <td>Total Items</td> 
                      <td><?php echo count($this->Items); ?></td>
                    </tr>  

                  </tbody></table>
                </div><!-- /.box-body -->
              </div>  
          </div>
          <div class="col-md-6" >  
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Account Information</h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tbody><tr> 
                      <th>Buyer Name</th>
                      <th><?php echo $this->Order->user->display_name; ?></th> 
                    </tr>
                    <tr> 
                      <td>Email</td> 
                      <td><a href="#"> <?php echo $this->Order->user->email; ?> </a> </td>
                    </tr> 

                    <tr> 
                      <td>Mobile</td> 
                      <td><a href="#"> <?php echo $this->Order->user->telephone; ?> </a> </td>
                    </tr> 

                  </tbody></table>
                </div><!-- /.box-body -->
              </div> 

          </div> 
        </div>  
          <div class="row">
            
            <div class="col-md-12">

                  <div class="box-header">
                  <h3 class="box-title">Prescriptions</h3>
                </div>
                  <ul class="mailbox-attachments clearfix">
                  <?php 
                  $prescriptions = array();
                  
                  if(strlen($this->Items [0]->prescriptions->attachments) > 0 ){
                       $prescriptions = explode(",", $this->Items[0]->prescriptions->attachments ); 
                  }
                   
                  if(strlen($prescriptions[0]) < 1 ){ unset($prescriptions[0]); }  
                  $i = 0; 
                   
                  foreach($prescriptions as $key => $name ) { ?>
                    <li> 
                      

                        <?php if( array_pop(explode(".", $name)) == 'pdf' ){ ?> 
                        
                          <span class="mailbox-attachment-icon"><i class="fa fa-file-pdf-o"></i></span>

                        <?php }else{ ?>
                            <span class="mailbox-attachment-icon has-img">
                            <img src="/application/static?type=prescriptions&name=<?php echo $name; ?>" alt="Attachment" style="  height: 130px;">
                            </span>  
                      <?php } ?>
                      

                      <div class="mailbox-attachment-info">
                        
                        <a target="__blank" href="/application/static?type=prescriptions&name=<?php echo $name; ?>" class="mailbox-attachment-name"><i class="fa fa-paperclip"></i> 
                        <?php echo "File-".$i; ?> </a>

                        <span class="mailbox-attachment-size">
                          &nbsp;
                          <a target="__blank" href="/application/static/download?type=prescriptions&name=<?php echo $name; ?>" class="btn btn-default btn-xs pull-right"><i class="fa fa-cloud-download"></i></a>

                          <a target="__blank" 
                              onclick="javascript:clickfunction('<?php echo '/application/static?type=prescriptions&name='.$name; ?>')"  
                              href="#" class="btn btn-default btn-xs pull-right"><i class="fa fa-print"></i></a>
                        </span>
                      </div>


                    </li>  
                  <?php  }   ?>  
                  </ul>
            </div>
          </div>

         <div class="row">
          <div class="col-md-6" > 
              <div class="box box-solid">
                  <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Billing Address</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                    <h3><?php echo ucwords($this->Order->billing_address->name); ?></h3>
                    <p><?php echo ucwords($this->Order->billing_address->street1); ?> , <?php echo ucwords($this->Order->billing_address->street2); ?></p>
                      <p>City: <?php echo ucwords($this->Order->billing_address->city); ?> </p>
                      <p>State: <?php echo ucwords($this->Order->billing_address->state); ?> </p>
                      <p>Country: <?php echo ucwords($this->Order->billing_address->country); ?></p> 
                    <h4>Pincode. <?php echo ucwords($this->Order->billing_address->pincode); ?> </h4>
                    
                  </div><!-- /.box-body -->
              </div>
            </div>
              <div class="col-md-6" >
              <div class="box box-solid">
                  <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Delivery Address</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                   
                     <h3><?php echo ucwords($this->Order->shipping_address->name); ?></h3>
                    <p><?php echo ucwords($this->Order->shipping_address->street1); ?> , <?php echo ucwords($this->Order->shipping_address->street2); ?></p>
                      <p>City: <?php echo ucwords($this->Order->shipping_address->city); ?> </p>
                      <p>State: <?php echo ucwords($this->Order->shipping_address->state); ?> </p>
                      <p>Country: <?php echo ucwords($this->Order->shipping_address->country); ?></p> 
                    <h4>Pincode. <?php echo ucwords($this->Order->shipping_address->pincode); ?> </h4>
                    

                    
                  </div><!-- /.box-body -->
              </div>

            </div>

          </div> 
          
          <div class="row">
              <div class="col-md-6" >
              <div class="box box-solid">
                  <div class="box-header with-border">
                    <i class="fa fa-user"></i>
                    <h3 class="box-title">Payment Information</h3>
                  </div><!-- /.box-header -->
                  <div class="box-body">
                   <p>Cash On Delivery Order was placed using CADs</p>
                  </div><!-- /.box-body -->
              </div>

            </div>  
        </div> 
        <div class="row">
            <div class="col-xs-12" >
            <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Items Ordered</h3> 
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table">
                    <tbody>
                      <tr>
                      <th>SubOrder ID</th>
                      <th>Item</th> 
                      <th>MRP</th>
                      <th>Price</th>
                      <th>Qty</th>
                      <th>Subtotal</th>
                      <th>Status</th>
                      <th>Select  All <input type="checkbox"  id="select_all"     > </th>
                    </tr>
                    <?php foreach ($this->Items as $key => $Item) { 

                            $trclass ="";
                            $lbclass="label label-success";
                            if(strtolower($Item->status) == 'removed' ){ 
                              $trclass = "bg-red";
                              $lbclass = "label label-info";
                            } 

                     ?> 
                          <tr id="tr_<?php echo $Item->id; ?>" class="<?php echo $trclass; ?>">
                            <td><?php echo $this->Order->id; ?>-<?php echo $Item->id; ?></td>
                            <td>
                             <?php 
                              if($Item->status != 'removed'){ ?> 
                                <?php echo ucwords($Item->product->name); ?> 
                            <?php }else{ ?>
                              <?php echo ucwords($Item->product->name); ?>
                             <?php } ?>
                            </td>
                            <td><?php echo "Rs. ".$Item->product->MRP; ?></td>
                            <td><?php echo "Rs. ".$Item->price; ?></td>
                            <td><span id="tr_qty_<?php echo $Item->id; ?>"><?php echo $Item->qty; ?></span> </td>
                            <td><?php echo ($Item->qty*$Item->price); ?></td>
                            <td>
                              <span id="tr_span_<?php echo $Item->id; ?>" class="<?php echo $lbclass; ?>"><?php echo ucwords($Item->status); ?></span> 
                              <!-- <a href="bg-red"><i class="fa fa-close"></i></a> -->
                            </td>

                            <td>
                              <?php 
                               // if($Item->status == 'added'){ ?> 
                               <!--  <span>
                              <a href="#" data-toggle="modal" data-orderid ="<?php echo $Item->orderId; ?>" data-target="#remove"  data-id="<?php echo $Item->id; ?>"  data-qty="<?php echo $Item->qty; ?>"  href="#"  ><i class="fa fa-edit"></i></a>

                              </span> -->

                               <?php  //}   ?>

                               <input type="checkbox" name="select" class="select" id="select_<?php echo $Item->id; ?>"  data-id="<?php echo $Item->id; ?>"  value="<?php echo $Item->id; ?>" data-qty="<?php echo $Item->qty; ?>"   >

                               
                            </td>

                          </tr>   
                      <?php } ?> 
                      <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th> 
                      <th colspan = "4" > 
                        <table class="table">
                              <tbody> 
                              <tr >
                                <td>Subtotal : </td> 
                                <td class="tr_subtotal">Rs.  <?php echo $this->Subtotal; ?>-/</td>
                              </tr>
                              <tr>
                                <td >Shiping Charge :</td> 
                                <td  class="tr_shiping" >Rs. <?php echo $this->ShipingCharge; ?>-/</td>
                              </tr>  
                              <tr>
                                <td >Offer Price :</td> 
                                <td class="tr_offer"> -Rs. <?php echo $this->OfferPrice; ?>-/</td>
                              </tr>  
                              <tr>
                                <td>Grand Total :</td> 
                                <td ><span class="badge bg-green tr_grand " >Rs. <?php echo $this->GrandTotal; ?>-/</span></td>
                              </tr>  
                            </tbody>
                        </table>
                    </th>
                  </tr>  

                  </tbody>
                  </table>
                </div><!-- /.box-body -->
              </div>
            </div>
        
        </div>

        <div class="row">  
        <div class="col-md-6"> 
              <!-- general form elements disabled -->
            <div class="box box-primary">
            <?php  
                echo $this->partial('partial/form-partial', array( 'form' => $this->form ) );
            ?>  
            </div> 
        </div> 


        </div>


        
        <?php } 
          if($this->print){ ?>

               <div class="row">
                <div class="col-sm-12">
                  <div class="box box-primary">
                    <div class="box-header with-border">
                      <h3 class="box-title">Order</h3>
                      <span class="label label-primary pull-right"><i class="fa fa-html5"></i></span>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                      <p> Printable Order Summary </p>
                      <a href="/ops/index/print?order=<?php echo $this->orderid; ?>" target="_blank" class="btn btn-primary"><i class="fa fa-print"></i> Print Order Details </a>
                    </div><!-- /.box-body -->
                  </div><!-- /.box -->
                </div><!-- /.col --> 
              </div> 
              <div class="row">
                <div class="col-sm-12">
                  <div class="timeline-item"> 
                    <h3 class="timeline-header">Printable Precription</h3>
                    <div class="timeline-body">  
                      <ul  class="mailbox-attachments clearfix">
                      <?php 
                        $prescriptions = array();
                        foreach ($this->Items as $key => $item ) {  
                             $prescriptions = explode(",", $item->prescriptions->attachments );    
                        }  
                        foreach($prescriptions as $key => $name ) { ?>
                          <li>  
                              <?php if( array_pop(explode(".", $name)) == 'pdf' ){ ?> 
                                <span class="mailbox-attachment-icon"><i class="fa fa-file-pdf-o"></i></span>

                              <?php }else{ ?>
                                  <span class="mailbox-attachment-icon has-img">
                                  <img src="/application/static?type=prescriptions&name=<?php echo $name; ?>" alt="Attachment">
                                  </span>  
                            <?php } ?> 

                            <div class="mailbox-attachment-info">
                              
                              <a target="__blank" href="/application/static?type=prescriptions&name=<?php echo $name; ?>" class="mailbox-attachment-name"><i class="fa fa-paperclip"></i> 
                              <?php echo $name; ?> </a>

                              <span class="mailbox-attachment-size">
                                &nbsp;
                                <a target="__blank" href="/application/static/download?type=prescriptions&name=<?php echo $name; ?>" class="btn btn-default btn-xs pull-right"><i class="fa fa-cloud-download"></i></a>

                                <a target="__blank" 
                                    onclick="javascript:clickfunction('<?php echo '/application/static?type=prescriptions&name='.$name; ?>')"  
                                    href="#" class="btn btn-default btn-xs pull-right"><i class="fa fa-print"></i></a>
                              </span>
                            </div> 
                          </li>  
                        <?php  }   ?>  

                      </ul> 
                    </div>
                  </div> 
                </div><!-- /.col --> 
              </div> 

        <?php  }  ?>
      </div> 
    </div> 
  </div> 
</div> 




<script type="text/javascript">
        $(function() {
            $("body").addClass('sidebar-collapse');
            
            $('#reason').closest('.form-group').hide(); 
            $('#reason').val("Other"); 
            $("#status").change(function(e){
                 if( $(this).val() == 'Returned' || $(this).val() == 'Cancelled' || $(this).val() == 'Process refund' || $(this).val() == 'Others' ){ 

                   $('#reason').closest('.form-group').show(); 

                 }else{ 

                    $('#reason').closest('.form-group').hide(); 
                    $('#reason').val("Other"); 
                 } 
            });  
            $(".select").click( function(e){  
                 var values = new Array();
                 $(".select:checkbox:checked").map(function(e1){ 
                      values.push($(this).val());  
                 }); 
                $("#suborder").val( values.toString() );
                
            }); 
            $("#select_all").click( function(e){ 
              var all = $(this);
              $('.select').each(function() {
                   $(this).prop("checked", all.prop("checked"));
              }); 

               var values = new Array();
               $(".select:checkbox:checked").map(function(e1){ 
                    values.push($(this).val());  
               });
              $("#suborder").val( values.toString() );


            }); 

        });   
        function clickfunction(url){   
           win = window.open("http://"+document.domain+url  , 'print' , "modal=yes"  ); 
           win.focus();
           win.print();
        }
</script>

