
<?php echo $this->doctype(); ?>
<html lang="en" >
  <head>
    <meta charset="UTF-8">
    <?php echo $this->headTitle('nDrugs '. $this->translate('Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))                          
            ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
            ->prependStylesheet($this->basePath('plugins/daterangepicker/daterangepicker-bs3.css'))
            ->prependStylesheet($this->basePath('plugins/datepicker/datepicker3.css'))
            ->prependStylesheet($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
            ->prependStylesheet($this->basePath('plugins/morris/morris.css')) 
            ->prependStylesheet($this->basePath('plugins/iCheck/flat/blue.css'))  
            ->prependStylesheet($this->basePath('css/skins/_all-skins.min.css'))  
            ->prependStylesheet($this->basePath('css/AdminLTE.min.css'))  
            ->prependStylesheet($this->basePath('plugins/ionicons-2.0.1/css/ionicons.min.css'))  
            ->prependStylesheet($this->basePath('plugins/font-awesome-4.3.0/css/font-awesome.min.css'))  
            ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?> 


             <?php echo $this->headScript() 
            //->prependFile($this->basePath('js/demo.js'))
            ->prependFile($this->basePath('js/aktel.js'))
            ->prependFile($this->basePath('js/pages/dashboard.js'))
            ->prependFile($this->basePath('js/app.min.js'))
            ->prependFile($this->basePath('plugins/jQuery-File-Upload/jquery.picture.cut.js')) 
            ->prependFile($this->basePath('plugins/fastclick/fastclick.min.js'))
            ->prependFile($this->basePath('plugins/slimScroll/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('plugins/iCheck/icheck.min.js'))
            ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
            ->prependFile($this->basePath('plugins/datepicker/bootstrap-datepicker.js'))
            ->prependFile($this->basePath('plugins/daterangepicker/daterangepicker.js'))
            ->prependFile($this->basePath('plugins/knob/jquery.knob.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
            ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
            ->prependFile($this->basePath('plugins/sparkline/jquery.sparkline.min.js'))
            ->prependFile($this->basePath('plugins/morris/morris.min.js'))
            ->prependFile($this->basePath('plugins/raphael/raphael-min.js'))

            ->prependFile($this->basePath('bootstrap/js/bootstrap.min.js'))  
            ->prependFile($this->basePath('plugins/underscore/underscore.js')) 
            ->prependFile($this->basePath('plugins/jQueryUI/1.11.2/jquery-ui.min.js'))
            ->prependFile($this->basePath('plugins/jQuery/jQuery-2.1.3.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>
 

 
</head>
<?php $children = $this->viewModel()->getCurrent()->getChildren();  ?>

  <body class="skin-blue">
   
<!-- Main content -->
        <section class="content">

          <?php echo $this->content; ?>  

        </section><!-- /.content --> 

    <?php echo $this->inlineScript() ?> 
    
  </body>
</html>